

// eslint-disable-next-line import/no-anonymous-default-export
export default[
    {
        id:1,
        title:"title1",
        description:"description1",
        price:100,
        cover:"../images/boy1.jpg",
        stats:{
            rating:6.0,
            review:23,
        },
        location:"Turkey",
        spots:39
    },
    {
        id:2,
        title:"title2",
        description:"description3",
        price:140,
        cover:"../images/boy2.jpg",
        stats:{
            rating:6.0,
            review:33,
        },
        location:"Turkey",
        spots:3
    },
    {
        id:3,
        title:"title3",
        description:"description3",
        price:200,
        cover:"../images/boy3.jpg",
        stats:{
            rating:8.0,
            review:12,
        },
        location:"Turkey",
        spots:6
    },
    {
        id:4,
        title:"title4",
        description:"description4",
        price:66,
        cover:"../images/boy4.jpg",
        stats:{
            rating:8.3,
            review:8,
        },
        location:"Turkey",
        spots:1
    },
]